spaceship:
  help: "Spaceship environment configuration."
  length: 2.5
  margin: 0.2
  agent_slack: 0.00
  frequency_ratio: 0.1
  target_noise_std: 0.05
  target_radius: 0.05
  corridor_episode_length:  15
  arena_episode_length: 45
  enable_reward_shaping: false
  is_arena: true
  reward_shaping_slack: 0.1
ballnd:
  help: "Ball-ND environment configuration."
  n: 1
  target_margin: 0.2
  agent_slack: 0.00
  episode_length: 30
  frequency_ratio: 0.1
  respawn_interval: 0.5
  target_noise_std: 0.05
  enable_reward_shaping: false
  reward_shaping_slack: 0.1
